"""empty message

Revision ID: 317c1e7bab30
Revises: 3d7d354db5dd
Create Date: 2019-09-02 09:36:02.623488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '317c1e7bab30'
down_revision = '3d7d354db5dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'isAdmin')
    op.add_column('user', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'isAdmin')
    op.add_column('token', sa.Column('isAdmin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
