"""empty message

Revision ID: 3655264c9c5e
Revises: 73355b3e76b9
Create Date: 2019-09-09 20:05:16.986040

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3655264c9c5e'
down_revision = '73355b3e76b9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('is_todos_done', 'todo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_foreign_key(None, 'is_todos_done', 'todos', ['todo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'is_todos_done', type_='foreignkey')
    op.alter_column('is_todos_done', 'todo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
