"""empty message

Revision ID: 3985c5fda281
Revises: 3655264c9c5e
Create Date: 2019-09-10 14:14:00.170811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3985c5fda281'
down_revision = '3655264c9c5e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('is_todos_done', 'todo_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('is_todos_done', 'todo_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
