"""empty message

Revision ID: 3d7d354db5dd
Revises: bcc671779da2
Create Date: 2019-09-02 09:35:18.677396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d7d354db5dd'
down_revision = 'bcc671779da2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('token', sa.Column('isAdmin', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('token', 'isAdmin')
    # ### end Alembic commands ###
