"""empty message

Revision ID: 73355b3e76b9
Revises: aaa13dafb25a
Create Date: 2019-09-09 15:30:41.439091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73355b3e76b9'
down_revision = 'aaa13dafb25a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'is_todos_done', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'is_todos_done', type_='foreignkey')
    # ### end Alembic commands ###
