"""empty message

Revision ID: 9468132bc7a4
Revises: 21dd58157b0c
Create Date: 2019-09-03 15:15:18.723010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9468132bc7a4'
down_revision = '21dd58157b0c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('isEdit', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'isEdit')
    # ### end Alembic commands ###
