"""empty message

Revision ID: a0d50a0ede1d
Revises: c28d88f644a5
Create Date: 2019-09-08 23:27:57.977863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0d50a0ede1d'
down_revision = 'c28d88f644a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('is_todos_done', sa.Column('sub_todo_id', sa.Integer(), nullable=True))
    op.add_column('is_todos_done', sa.Column('todo_id', sa.Integer(), nullable=True))
    op.drop_column('is_todos_done', 'todos_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('is_todos_done', sa.Column('todos_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('is_todos_done', 'todo_id')
    op.drop_column('is_todos_done', 'sub_todo_id')
    # ### end Alembic commands ###
