"""empty message

Revision ID: aaa13dafb25a
Revises: a0d50a0ede1d
Create Date: 2019-09-09 11:27:18.185885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aaa13dafb25a'
down_revision = 'a0d50a0ede1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'is_todos_done', 'sub_todos', ['sub_todo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'is_todos_done', type_='foreignkey')
    # ### end Alembic commands ###
